### ISSUE TITLE
Version 2.29?

### ISSUE THREAD

**Issue by SoniEx2** [nplab/thttpd#4]
Version 2.29 upstream brings "Allow CGI to handle HTTP methods besides GET/HEAD/POST." This would be an useful (and even necessary) feature for me (altho I am not *currently* doing anything that needs PUT/PATCH/DELETE).

**Comment by tuexen** [comment]
Integrate upstream changes in
* [Integrate changes from upstream 2.27 -> 2.28](https://github.com/nplab/thttpd/commit/c6b64d60bee71ba11f44c0d8c1a87fb474e1cba9)
* [Integrate changes from upstream 2.28 -> 2.29](https://github.com/nplab/thttpd/commit/7cb6e4e9b646f5202794110237298ea762760408)
